# MySQL Dev (VPS)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_factura_marisco
spring.datasource.username=cangrivic_user
spring.datasource.password=Cangrivic2024!

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Logging específico para servicios
logging.level.com.facturas.cangrivic.service=DEBUG


# No usar SSL en dev local
# HTTPS
server.port=443
server.ssl.key-store=/opt/cangrivic/ssl/cangrivic.p12
server.ssl.key-store-password=Cangrivic2024!
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=cangrivic