# MySQL Dev (VPS)
spring.application.name=cangrivic
server.port=8085
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_factura_marisco?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Juan1997..

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security.web.*=debug
spring.jpa.show-sql=true

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Logging específico para servicios
logging.level.com.facturas.cangrivic.service=DEBUG

