# Nombre de la aplicación
spring.application.name=cangrivic

# Perfil por defecto
spring.profiles.active=dev

# Puerto por defecto
server.port=8085

# Configuración de logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=true
logging.level.com.facturas.cangrivic=DEBUG
spring.main.allow-bean-definition-overriding=true
server.error.include-message=always
